/* eslint-disable @stylistic/max-len */

const en = {
    motion_movesteps: 'This block moves the sprite forward by the number of steps you choose.',
    motion_turnright: 'This block turns the sprite to the right by the number of degrees you choose.',
    motion_turnleft: 'This block turns the sprite to the left by the number of degrees you choose.',
    motion_pointindirection: 'This block points the sprite in a direction. Ninety points right, zero points up, and one hundred eighty points down.',
    motion_pointtowards: 'This block turns the sprite so it points toward the mouse pointer or another sprite.',
    motion_pointtowards_menu: 'This menu lets you choose what the sprite should point toward.',
    motion_gotoxy: 'This block jumps the sprite to an exact place on the stage using x and y numbers.',
    motion_goto: 'This block jumps the sprite to the mouse pointer, a random position, or another sprite.',
    motion_goto_menu: 'This menu lets you choose where the sprite should go.',
    motion_glidesecstoxy: 'This block smoothly slides the sprite to an x and y place over the number of seconds you choose.',
    motion_glideto: 'This block smoothly slides the sprite to the mouse pointer, a random position, or another sprite.',
    motion_glideto_menu: 'This menu lets you choose where the sprite should glide.',
    motion_changexby: 'This block moves the sprite left or right. A bigger x number moves it right. A smaller or negative number moves it left.',
    motion_setx: 'This block puts the sprite at the x position you choose. X controls left and right.',
    motion_changeyby: 'This block moves the sprite up or down. A bigger y number moves it up. A smaller or negative number moves it down.',
    motion_sety: 'This block puts the sprite at the y position you choose. Y controls up and down.',
    motion_ifonedgebounce: 'This block makes the sprite turn around when it touches the edge of the stage.',
    motion_setrotationstyle: 'This block chooses how the sprite can turn: all around, left and right, or not at all.',
    motion_xposition: 'This reporter tells you the sprite position from left to right.',
    motion_yposition: 'This reporter tells you the sprite position from bottom to top.',
    motion_direction: 'This reporter tells you which way the sprite is pointing.',
    motion_scroll_right: 'This old block is kept for older projects. It does not change new Scratch projects.',
    motion_scroll_up: 'This old block is kept for older projects. It does not change new Scratch projects.',
    motion_align_scene: 'This old block is kept for older projects. It does not change new Scratch projects.',
    motion_xscroll: 'This old reporter is kept for older projects. It does not change new Scratch projects.',
    motion_yscroll: 'This old reporter is kept for older projects. It does not change new Scratch projects.',

    looks_say: 'This block makes the sprite show words in a speech bubble.',
    looks_sayforsecs: 'This block makes the sprite show words in a speech bubble for the number of seconds you choose.',
    looks_think: 'This block makes the sprite show words in a thought bubble.',
    looks_thinkforsecs: 'This block makes the sprite show words in a thought bubble for the number of seconds you choose.',
    looks_show: 'This block makes the sprite appear on the stage.',
    looks_hide: 'This block makes the sprite disappear from the stage.',
    looks_hideallsprites: 'This block hides all sprites on the stage.',
    looks_changeeffectby: 'This block changes a picture effect, like color or brightness, by the amount you choose.',
    looks_seteffectto: 'This block sets a picture effect, like color or brightness, to the exact amount you choose.',
    looks_cleargraphiceffects: 'This block removes all picture effects and makes the sprite look normal again.',
    looks_changesizeby: 'This block makes the sprite bigger or smaller by the amount you choose.',
    looks_setsizeto: 'This block sets the sprite size to an exact percent.',
    looks_size: 'This reporter tells you the sprite size percent.',
    looks_changestretchby: 'This block stretches the sprite wider or thinner by the amount you choose.',
    looks_setstretchto: 'This block sets how stretched the sprite is.',
    looks_switchcostumeto: 'This block changes the sprite to the costume you choose.',
    looks_costume: 'This menu lets you choose a costume.',
    looks_nextcostume: 'This block changes the sprite to the next costume in its list.',
    looks_switchbackdropto: 'This block changes the stage to the backdrop you choose.',
    looks_backdrops: 'This menu lets you choose a backdrop.',
    looks_nextbackdrop: 'This block changes the stage to the next backdrop.',
    looks_switchbackdroptoandwait: 'This block changes the backdrop and waits until scripts started by that change finish.',
    looks_gotofrontback: 'This block moves the sprite to the front layer or the back layer.',
    looks_goforwardbackwardlayers: 'This block moves the sprite forward or backward through the picture layers.',
    looks_backdropnumbername: 'This reporter tells you the current backdrop number or name.',
    looks_costumenumbername: 'This reporter tells you the current costume number or name.',

    sound_play: 'This block starts playing the sound you choose, then the next block can start right away.',
    sound_playuntildone: 'This block plays the sound you choose and waits until the sound is finished.',
    sound_sounds_menu: 'This menu lets you choose a sound.',
    sound_stopallsounds: 'This block stops every sound that is playing.',
    sound_seteffectto: 'This block sets a sound effect, like pitch or pan, to the exact amount you choose.',
    sound_changeeffectby: 'This block changes a sound effect, like pitch or pan, by the amount you choose.',
    sound_cleareffects: 'This block removes sound effects and makes sounds play normally again.',
    sound_changevolumeby: 'This block makes the sprite sounds louder or quieter by the amount you choose.',
    sound_setvolumeto: 'This block sets the sprite volume to an exact percent.',
    sound_volume: 'This reporter tells you the sprite volume percent.',

    event_whenflagclicked: 'This hat block starts the blocks under it when the green flag is clicked.',
    event_whenkeypressed: 'This hat block starts the blocks under it when the chosen key is pressed.',
    event_whenthisspriteclicked: 'This hat block starts the blocks under it when this sprite is clicked.',
    event_whenstageclicked: 'This hat block starts the blocks under it when the stage is clicked.',
    event_whenbackdropswitchesto: 'This hat block starts the blocks under it when the stage changes to the chosen backdrop.',
    event_whengreaterthan: 'This hat block starts the blocks under it when the chosen sensor number gets bigger than your number.',
    event_whenbroadcastreceived: 'This hat block starts the blocks under it when it receives the message you choose.',
    event_broadcast: 'This block sends a message so other scripts can start.',
    event_broadcastandwait: 'This block sends a message and waits until the scripts that hear it finish.',
    event_broadcast_menu: 'This menu lets you choose a message to send or receive.',
    event_whentouchingobject: 'This hat block starts when the sprite touches the object you choose.',
    event_touchingobjectmenu: 'This menu lets you choose what touching object to check.',

    control_wait: 'This block pauses the script for the number of seconds you choose.',
    control_repeat: 'This repeat loop runs the blocks inside it again and again for the number of times you choose.',
    control_forever: 'This forever loop keeps running the blocks inside it over and over until the project stops.',
    control_if: 'This block checks a question. If the answer is yes, it runs the blocks inside.',
    control_if_else: 'This block checks a question. If yes, it runs the first blocks. If no, it runs the other blocks.',
    control_wait_until: 'This block pauses the script until the question inside becomes yes.',
    control_repeat_until: 'This repeat until loop keeps running the blocks inside until the question becomes yes.',
    control_stop: 'This block stops scripts. The menu chooses which scripts to stop.',
    control_start_as_clone: 'This hat block starts the blocks under it when this sprite becomes a clone.',
    control_create_clone_of: 'This block makes a copy, called a clone, of the sprite you choose.',
    control_create_clone_of_menu: 'This menu lets you choose which sprite to clone.',
    control_delete_this_clone: 'This block deletes this clone from the stage.',
    control_while: 'This while loop keeps running the blocks inside while the question is yes.',
    control_for_each: 'This for each loop counts with a variable and runs the blocks inside for each number.',
    control_get_counter: 'This reporter gives the value of the old counter used by older Scratch projects.',
    control_incr_counter: 'This old block adds one to the old counter.',
    control_clear_counter: 'This old block sets the old counter back to zero.',
    control_all_at_once: 'This block runs the blocks inside together for older Scratch projects.',

    sensing_touchingobject: 'This question block is yes when the sprite is touching the object you choose.',
    sensing_touchingobjectmenu: 'This menu lets you choose what the sprite might be touching.',
    sensing_touchingcolor: 'This question block is yes when the sprite is touching the color you choose.',
    sensing_coloristouchingcolor: 'This question block is yes when one color on the sprite is touching another color.',
    sensing_distanceto: 'This reporter tells you how far the sprite is from the mouse pointer or another sprite.',
    sensing_distancetomenu: 'This menu lets you choose what distance to measure.',
    sensing_askandwait: 'This block asks a question on the stage and waits for the child to type an answer.',
    sensing_answer: 'This reporter gives the last answer typed after an ask block.',
    sensing_keypressed: 'This question block is yes when the chosen key is being pressed.',
    sensing_keyoptions: 'This menu lets you choose a keyboard key.',
    sensing_mousedown: 'This question block is yes when the mouse button is being pressed.',
    sensing_mousex: 'This reporter tells you the mouse position from left to right.',
    sensing_mousey: 'This reporter tells you the mouse position from bottom to top.',
    sensing_setdragmode: 'This block chooses whether the sprite can be dragged by hand on the stage.',
    sensing_loudness: 'This reporter tells you how loud the microphone sound is.',
    sensing_loud: 'This old question block is yes when the microphone sound is loud.',
    sensing_timer: 'This reporter tells you how many seconds have passed since the timer was reset.',
    sensing_resettimer: 'This block sets the timer back to zero.',
    sensing_of: 'This reporter tells you a chosen fact, like x position or costume, about a sprite or the stage.',
    sensing_of_object_menu: 'This menu lets you choose which sprite or stage to read from.',
    sensing_current: 'This reporter tells you a part of the current date or time, like year, hour, or second.',
    sensing_dayssince2000: 'This reporter tells you how many days have passed since the year two thousand started.',
    sensing_online: 'This question block is yes when Scratch is connected to the internet.',
    sensing_username: 'This reporter tells you the Scratch username.',
    sensing_userid: 'This old reporter is kept for older projects.',

    operator_add: 'This reporter adds two numbers and gives the answer.',
    operator_subtract: 'This reporter subtracts the second number from the first number.',
    operator_multiply: 'This reporter multiplies two numbers and gives the answer.',
    operator_divide: 'This reporter divides the first number by the second number.',
    operator_random: 'This reporter picks a random number between the two numbers you choose.',
    operator_lt: 'This question block is yes when the first number is smaller than the second number.',
    operator_equals: 'This question block is yes when the two things are the same.',
    operator_gt: 'This question block is yes when the first number is bigger than the second number.',
    operator_and: 'This question block is yes only when both questions inside are yes.',
    operator_or: 'This question block is yes when at least one question inside is yes.',
    operator_not: 'This question block flips the answer. Yes becomes no, and no becomes yes.',
    operator_join: 'This reporter sticks two pieces of text together.',
    operator_letter_of: 'This reporter gives one letter from a piece of text.',
    operator_length: 'This reporter tells how many letters are in a piece of text.',
    operator_contains: 'This question block is yes when the first text has the second text inside it.',
    operator_mod: 'This reporter gives the leftover amount after division.',
    operator_round: 'This reporter rounds a number to the nearest whole number.',
    operator_mathop: 'This reporter does the math action you choose, like square root or absolute value.',

    data_variable: 'This reporter gives the value saved in the variable you choose.',
    data_setvariableto: 'This block saves a new value in the variable you choose.',
    data_changevariableby: 'This block changes a variable by adding the number you choose.',
    data_showvariable: 'This block shows the variable watcher on the stage.',
    data_hidevariable: 'This block hides the variable watcher from the stage.',
    data_listcontents: 'This reporter gives the items saved in the list you choose.',
    data_listindexall: 'This small value chooses an item number, the last item, or all items in a list.',
    data_listindexrandom: 'This small value chooses an item number, the last item, or a random item in a list.',
    data_addtolist: 'This block adds a new item to the end of the list you choose.',
    data_deleteoflist: 'This block removes one item from the list you choose.',
    data_deletealloflist: 'This block removes every item from the list you choose.',
    data_insertatlist: 'This block puts a new item into the list at the place you choose.',
    data_replaceitemoflist: 'This block changes one item in the list to a new item.',
    data_itemoflist: 'This reporter gives one item from the list.',
    data_itemnumoflist: 'This reporter finds where an item is in the list.',
    data_lengthoflist: 'This reporter tells how many items are in the list.',
    data_listcontainsitem: 'This question block is yes when the list has the item you choose.',
    data_showlist: 'This block shows the list watcher on the stage.',
    data_hidelist: 'This block hides the list watcher from the stage.',

    procedures_definition: 'This block holds your custom block script. The blocks under it run when your custom block is used.',
    procedures_prototype: 'This block shows the shape and inputs of your custom block.',
    procedures_call: 'This block runs the custom block you made.',
    procedures_declaration: 'This block lets you name and set up a custom block.',
    argument_reporter_string_number: 'This reporter gives the text or number input passed into a custom block.',
    argument_reporter_boolean: 'This question reporter gives the yes or no input passed into a custom block.',
    argument_editor_string_number: 'This input lets you add a text or number spot to a custom block.',
    argument_editor_boolean: 'This input lets you add a yes or no spot to a custom block.',

    math_number: 'This is a number value you can type into another block.',
    math_positive_number: 'This is a positive number value you can type into another block.',
    math_whole_number: 'This is a whole number value you can type into another block.',
    math_integer: 'This is an integer value you can type into another block.',
    math_angle: 'This is an angle value used for turning or pointing.',
    colour_picker: 'This value lets you choose a color.',
    matrix: 'This value lets you choose dots in a small grid.',
    note: 'This value lets you choose a music note.',
    text: 'This is text you can type into another block.'
};

const fr = {
    motion_movesteps: 'Ce bloc fait avancer le lutin du nombre de pas choisi.',
    motion_changexby: 'Ce bloc deplace le lutin a gauche ou a droite. Un nombre x plus grand le deplace a droite. Un nombre plus petit ou negatif le deplace a gauche.',
    motion_changeyby: 'Ce bloc deplace le lutin en haut ou en bas. Un nombre y plus grand le deplace en haut. Un nombre plus petit ou negatif le deplace en bas.',
    sound_play: 'Ce bloc demarre le son choisi. Le script peut continuer sans attendre la fin du son.',
    sound_playuntildone: 'Ce bloc joue le son choisi et attend que le son soit fini avant de continuer.',
    control_if_else: 'Ce bloc pose une question. Si la reponse est oui, il lance les premiers blocs. Sinon, il lance les autres blocs.',
    operator_add: 'Ce bloc additionne deux nombres et donne la reponse.',
    data_changevariableby: 'Ce bloc change une variable en ajoutant le nombre choisi.'
};

const DEFAULT_EXPLANATIONS_BY_LOCALE = {
    en,
    fr
};

export {
    DEFAULT_EXPLANATIONS_BY_LOCALE
};
